actions/urls.py
from django.conf.urls import url
from .views import snippet_upvote, bookmark_snippets

app_name = "actions"

urlpatterns = [
    url(r'^upvote/$', snippet_upvote, name="upvote"),
    url(r'^bookmark/$', bookmark_snippets, name="bookmark")
]

snippet_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_title = "Snippet Admin"
admin.site.site_header = "Snippet Admin"
admin.site.index_title = "Snippet Administration"

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'', include('snippets.urls', namespace='snippets')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^actions/', include('actions.urls', namespace='actions'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

snippets/urls.py
from django.conf.urls import url
from .views import (
    IndexView,
    AddSnippetView,
    LanguageRegisterView,
    SnippetDetailView,
    FilterView,
    FilterByView,
    PersonalSnippetView,
    SnippetDeleteView,
    SnippetUpdateView,
    SearchView,)

app_name = "snippets"

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^snippets/add/$', AddSnippetView.as_view(), name="add_snippet"),
    url(r'^snippets/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        SnippetDetailView.as_view(), name='snippet_detail'),
    url(r'^snippets/personal/view/$', PersonalSnippetView.as_view(),
        name="personal_snippets"),
    url(r'^snippets/languages/$', FilterByView.as_view(), name="lang_view"),
    url(r'^snippets/languages/(?P<pk>\d+)/$',
        FilterView.as_view(), name="lang_filter"),
    url(r'^snippets/author/$', FilterByView.as_view(), name="author_view"),
    url(r'^snippets/category/$', FilterByView.as_view(), name="category_view"),
    url(r'^snippet/author/(?P<pk>\d+)/$',
        FilterView.as_view(), name="author_filter"),
    url(r'^snippet/category/(?P<pk>\d+)/$',
        FilterView.as_view(), name="category_filter"),

    url(r'^snippets/edit/(?P<pk>\d+)/$', SnippetUpdateView.as_view(), name="edit_snippet"),
    url(r'^snippets/(?P<pk>\d+)/delete$', SnippetDeleteView.as_view(),
        name="del_snippet"),
    url(r'^search/$', SearchView.as_view(), name='snippet_search'),
    url(r'^lang/reg/$', LanguageRegisterView.as_view(), name="language_register"),
    
]

snippets/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Language(models.Model):
    name = models.CharField(max_length=50)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='languages')
    language_mode = models.CharField(max_length=50, default='')
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = 'name',


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"
        ordering = 'name',


class Snippet(models.Model):
    title = models.CharField(max_length=200)
    language = models.ForeignKey(Language, related_name='snippets')
    category = models.ManyToManyField(Category, related_name='snippets')
    slug = models.SlugField(unique_for_date='created', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="snippets_created")
    description = models.TextField(max_length=300)
    code = models.TextField()
    upvotes = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="snippets_upvoted", blank=True)
    downvotes = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="snippets_downvoted", blank=True)
    bookmarks = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="bookmarked_snippets", blank=True)
    sample_input = models.TextField(blank=True)
    sample_output = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Snippet, self).save(*args, **kwargs)
        

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("snippets:snippet_detail", args=[self.pk, self.slug])

    class Meta:
        ordering = '-created',

snippets/forms.py
from django import forms
from .models import Snippet, Language


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        exclude = ('author', 'created', 'slug', 'upvotes', 'downvotes',
            'bookmarks')

        widgets = {
            'title': forms.TextInput(attrs={'class': "form-control1",
                "placeholder": "Add a Title"}),
            'language': forms.Select(attrs={'class': 'form-control1'}),
            'category': forms.SelectMultiple(attrs={'class': 'form-control1'}),
            'description': forms.Textarea(attrs={
                'class': 'form-control1 form-control',
                'cols': 5,
                'placeholder': "Enter a short Description of snippet"}),
            'code': forms.Textarea(attrs={
                'class': 'form-control1 form-control',
                'rows': 15, 'placeholder': "Enter Snippet"}),
            'sample_input': forms.Textarea(attrs={
                'class': 'form-control1 form-control',
                'cols': 5, 'placeholder': "Enter a sample input"}),
            'sample_output': forms.Textarea(attrs={
                'class': 'form-control1 form-control',
                'cols': 5, 'placeholder': "Enter a sample output"}),
        }
        help_texts = {
            'category': ("Hold down 'Control', or 'Command' on a Mac, to select more than one.")
        }

class LanguageForm(forms.Form):
    CHOICES = Language.objects.values_list('id', 'name')

    language = forms.MultipleChoiceField(choices=CHOICES, widget=forms.CheckboxSelectMultiple)
    

snippets/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from django.views.generic import ListView, View, DetailView, TemplateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, FormView, DeleteView
from .models import Snippet, Language, Category
from .forms import SnippetForm, LanguageForm
from haystack.query import SearchQuerySet


class IndexView(ListView):
    template_name = "snippets/index.html"
    model = Snippet
    context_object_name = "snippet_list"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['lang_form'] = LanguageForm

        return context


@method_decorator(login_required, name="dispatch")
class AddSnippetView(FormView):
    form_class = SnippetForm
    template_name = "snippets/add_snippet.html"
    success_url = reverse_lazy("snippets:index")
    initial = {'language': Language.objects.first()}

    def form_valid(self, form_class, *args, **kwargs):
        categories = form_class.cleaned_data['category']
        new_snippet = form_class.save(commit=False)
        new_snippet.author = self.request.user
        new_snippet.save()
        for index in categories:
            new_snippet.category.add(index)
        return super(AddSnippetView, self).form_valid(form_class, *args, **kwargs)


class SnippetDetailView(DetailView):
    model = Snippet
    template_name = "snippets/snippet_detail.html"
    context_object_name = 'snippet'


class FilterView(ListView):
    """Display snippets on the index page after the user has
    chosen to filter snippets by either language, author or Categories"""
    template_name = "snippets/index.html"
    context_object_name = "snippet_list"

    def get_queryset(self, *args, **kwargs):
        # Get the pk of the clicked object from the PATH_INFO key of the
        # META variable
        model = snip = ''
        self.md = self.request.META['PATH_INFO'].split("/")[2]
        pk = self.request.META['PATH_INFO'].split("/")[3]

        models = {'languages': Language, 'author': User, 'category': Category}
        model = models[self.md]
    
        self.qs = model.objects.filter(pk=pk).first()

        try:
            snip = self.qs.snippets.all()
        except:
            snip = self.qs.snippets_created.all()

        return snip

    def get_context_data(self, **kwargs):
        context = super(FilterView, self).get_context_data(**kwargs)
        context['md'] = self.md
        context['qs'] = self.qs

        return context


class FilterByView(ListView):
    """Filter snippets by languages, category and author"""
    template_name = "snippets/filter.html"

    def get_queryset(self, *args, **kwargs):
        # get the name of the model from the url

        md = self.request.META['PATH_INFO'].split("/")[2]
        model = self.lang = self.user = self.category = ''
        
        if md == "languages":
            model = Language
            self.lang = True
        elif md == "author":
            model = User
            self.user = True
        elif md == "category":
            model = Category
            self.category = True

        self.qs = model.objects.all()

        return self.qs

    def get_context_data(self, **kwargs):
        context = super(FilterByView, self).get_context_data(**kwargs)
        context['lang'] = self.lang
        context['user'] = self.user
        context['category'] = self.category

        return context


@method_decorator(login_required, name="dispatch")
class PersonalSnippetView(TemplateView):
    template_name = "snippets/personal_snippets.html"


@method_decorator(login_required, name='dispatch')
class SnippetUpdateView(UpdateView):
    model = Snippet
    form_class = SnippetForm
    template_name = "snippets/edit_snippet.html"


@method_decorator(login_required, name='dispatch')
class SnippetDeleteView(DeleteView):
    model = Snippet
    success_url = reverse_lazy("snippets:personal_snippets")


class SearchView(ListView):
    """A view to perform search"""
    template_name = "snippets/search.html"

    def get_queryset(self, *args, **kwargs):
        qs = Snippet.objects.all()
        self.query = self.request.GET.get("q", None)

        if self.query is not None:
            qs = qs.filter(
                Q(title__icontains=self.query) |
                Q(description__icontains=self.query) |
                Q(author__username__icontains=self.query) |
                Q(code__icontains=self.query) |
                Q(language__name__icontains=self.query))

        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)
        context['query'] = self.query

        return context


@method_decorator(login_required, name="dispatch")
class LanguageRegisterView(FormView):
    """Displays a form for the user to choose the languages he is
    currently working with.
    """
    form_class = LanguageForm
    http_method_names = ['post']

    def form_valid(self, form, *args, **kwargs):
        cd = form.cleaned_data
        for pk in cd['language']:
            lang = get_object_or_404(Language, pk=int(pk))
            self.request.user.languages.add(lang)

        return render(self.request, 'accounts/profile.html')

snippets/templates/snippets/add_snippet.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Add Snippet
{% endblock title %}
{% block content %}
<div id="page-wrapper" class="gray-bg dashbard-1">
 <div class="content-main">
  <div class="grid-form1">
   <h3>Add a snippet</h3>
   <div class="tab-content">
    <div class="tab-pane active" id="horizontal-form">

      <form action="" method="post" accept-charset="utf-8" class="form-horizontal">
        {% csrf_token %}
        {% include 'snippet_form.html' %}
        <label for="editor" class="col-sm-2 control-label">Code</label>
        <div id="editor" class="col-sm-8">function foo(items) {
          var x = "All this is syntax highlighted";
          return x;
        }</div>
        <div class="profile-btn">

          <button type="submit" class="btn bg-red">Add Snippet</button>
          <div class="clearfix"></div>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>
<script src="{% static "snippets/js/vendor/src-noconflict/ace.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "snippets/js/vendor/src-noconflict/mode-actionscript.js" %}" type="text/javascript" charset="utf-8" id="script"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/python");
    var textarea = $('textarea#id_code').hide();
    editor.getSession().setValue(textarea.val());
    editor.getSession().on('change', function(){
      textarea.val(editor.getSession().getValue());
    });
    $("#id_language").change(function(event, l) {
      /* Act on the event */
      var lang = $("#id_language option[value="+$(this)[0].value.toString() +"]")[0].attributes[1].nodeValue
      var mode = "static/snippets/js/vendor/sr-noconflict/mode-" + lang + ".js"
      $("#script").attr('src', mode);
      editor.getSession().setMode("ace/mode/" + lang);
      
    });
</script>
{% endblock content %}

snippets/templates/snippets/edit_snippet.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Add Snippet
{% endblock title %}
{% block content %}
<div id="page-wrapper" class="gray-bg dashbard-1">
 <div class="content-main">
  <div class="grid-form1">
   <h3>Edit a snippet</h3>
   <div class="tab-content">
    <div class="tab-pane active" id="horizontal-form">

      <form method="post" class="form-horizontal" action="">
        {% csrf_token %}
        {% include 'snippet_form.html' %}
        <label for="editor" class="col-sm-2 control-label">Code</label>
        <div id="editor" class="col-sm-8">function foo(items) {
          var x = "All this is syntax highlighted";
          return x;
        }</div>
        <div class="profile-btn" style="clear: both;">

          <input type="submit" class="btn bg-red" value="Add Snippet">
          <div class="clearfix"></div>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>
<script src="{% static "snippets/js/vendor/src-noconflict/ace.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static "snippets/js/vendor/src-noconflict/mode-actionscript.js" %}" type="text/javascript" charset="utf-8" id="script"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/python");
    var textarea = $('textarea#id_code').hide();
    editor.getSession().setValue(textarea.val());
    editor.getSession().on('change', function(){
      textarea.val(editor.getSession().getValue());
    });
    $("#id_language").change(function(event, l) {
      /* Act on the event */
      var lang = $("#id_language option[value="+$(this)[0].value.toString() +"]")[0].attributes[1].nodeValue
      var mode = "static/snippets/js/vendor/sr-noconflict/mode-" + lang + ".js"
      $("#script").attr('src', mode);
      editor.getSession().setMode("ace/mode/" + lang);
      
    });
</script>
{% endblock content %}

snippets/templates/snippets/filter.html
{% extends "base_foundations.html" %}

{% block title %}
    Languages
{% endblock title %}

{% block content %}
<h1 class="text-center">{% if lang %}All languages{% elif user %}All Users{% elif category %}{% endif %}</h1>
<ul class="list-unstyled grid-x medium-up-4">
  {% for obj in object_list %}
    {% if lang %}
      <li class="cell"><a href="{% url 'snippets:lang_filter' obj.pk %}" class="green-a-tag">{{ obj.name }}</a></li>
    {% elif user %}
    <li class="cell"><a href="{% url 'snippets:author_filter' obj.pk %}" class="green-a-tag">{{ obj.username }}</a></li>
    {% elif category %}
    <li class="cell"><a href="{% url 'snippets:category_filter' obj.pk %}" class="green-a-tag">{{ obj.name }}</a></li>

    {% endif %}
  {% endfor %}
</ul>
  
{% endblock content %}

snippets/templates/snippets/index.html
{% extends "base_foundations.html" %}

{% load snippet_tags %}

{% load static %}

{% block title %}
    Snippets
{% endblock title %}

{% block content %}
<div id="main-body" class="grid-x grid-margin-x">
    
  <div class="medium-7 cell" id="snippets">
    <h3 class="text-center green-a-tag">{% if md == "languages" %}All "{{ qs }}" snippets{% elif md == "author" %}All Snippets written by "{{ qs }}"{% elif md == "category" %}All snippets in the "{{ qs }}" category{% endif %}</h3>
    {% for snippet in snippet_list %}
    <div class="callout">
      <h3><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></h3>
      <p>
        {{ snippet.description }}
      </p>
      <div class="code-detail float-right">
        <span>posted by </span><a href="{% url 'profile_view' pk=snippet.author.pk username=snippet.author.username %}">{{ snippet.author }}</a> on {{ snippet.created }}
        <span>language </span><a href="#">{{ snippet.language.name }}</a>
      </div><!-- / code detail -->
      
      <div id="snippet-{{ forloop.counter }}" class="editor">{{ snippet.code }}
      </div> <!-- / code -->

      <div class="code-actions float-left">
        <a href="#" title="Upvote Snippet" data-id="{{ snippet.id }}" data-action="upvote" id="upvote" js-post-upvote-url="{% url 'actions:upvote' %}">
          <span class="fa fa-chevron-up"></span>
        </a>
        &nbsp;&nbsp;
        <a href="#" title="Downvote Snippet" data-id="{{ snippet.id }}" data-action="downvote" id="downvote" js-post-upvote-url="{% url 'actions:upvote' %}">
          <span class="fa fa-chevron-down"></span>
        </a>
        &nbsp;&nbsp;
        <a href="#" title="Bookmark Snippet" id="bookmark" data-id="{{ snippet.id }}" data-action="bookmark" js-post-bookmark-url="{% url 'actions:bookmark' %}">
          <span class="fa fa-bookmark"></span>
        </a>
        
      </div><!-- / code actions -->
      <div class="code-stat float-right">
        <span class="fa fa-eye" title="views"> 6000</span> &nbsp;&nbsp;
        <span class="fa fa-chevron-up" title="upvotes"> {{ snippet.upvotes.count }}</span> &nbsp;&nbsp;
        <span class="fa fa-chevron-down" title="downvotes"> {{ snippet.downvotes.count }}</span>

      </div> <!-- / code stats -->
    </div>
    {% empty %}
      <p class="text-center">No Snippets Yet.</p>
    {% endfor %}

    {% include "pagination.html" %}
  </div>

  <div id="sidebar" class="medium-5 cell" data-sticky-container>
    <div class="sticky" data-sticky data-anchor="snippets">
      <div class="callout">
        <h3>Latest Snippets</h3>
        {% show_latest_snippets %}
      </div>
      <div class="callout">
        <h3>Most popular languages</h3>
        {% get_most_popular_languages as most_popular_languages %}
        <ul class="list-unstyled">
          {% for lang in most_popular_languages %}
          <li>
            <a href="{% url 'snippets:lang_filter' lang.pk %}">{{ lang.name }}</a>
          </li>
          {% empty %}
            <li>
              <p class="text-center">No popular posts yet.</p>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="callout">
        <h3>Top authors</h3>
        {% get_top_authors as top_authors %}
        <ul class="list-unstyled">
          {% for author in top_authors %}
          <li>
            <a href="{% url 'profile_view' author.pk author.username %}">{{ author.username }} </a>
          </li>
          {% empty %}
            <li>
              No top authors yet.
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

{% include "snippets/lang_modal.html" %}

<script src="{% static "snippets/js/vendor/src-noconflict/ace.js" %}" type="text/javascript" charset="utf-8"></script>

<script src="static/snippets/js/vendor/src-noconflict/mode-coffee.js" type="text/javascript" charset="utf-8" id="script"></script>
<script>
  {% for snippet in snippet_list %}
    var editor = ace.edit("snippet-{{ forloop.counter }}");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/{{ snippet.language.language_mode }}");
    editor.setReadOnly(true);
  {% endfor %}  
</script>

{% endblock content %}

snippets/templates/snippets/lang_modal.html
<p><button class="button" data-open="exampleModal11" id="open-tech">Click me for a modal</button></p>

<div class="large reveal" id="exampleModal11" aria-labelledby="exampleModalHeader11" data-reveal>
  <h1 id="exampleModalHeader11" class="h3">Select your technology</h1>
  <form action="{% url 'snippets:language_register' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <fieldset>
      <legend>Select your technology</legend>
        {{ lang_form }}
    </fieldset>
    <input type="submit" class="button" value="Save">
  </form>
  <button class="close-button" data-close aria-label="Close Accessible Modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

snippets/templates/snippets/latest_snippets.html
<ul style="list-style: none">
  {% for snippet in latest_snippets %}
    <li>
      <a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a>
    </li>
  {% endfor %}
</ul>

snippets/templates/snippets/personal_snippets.html
{% extends "base_foundations.html" %}
{% block title %}
    Your Snippets
{% endblock title %}


{% block content %}
  
  <div>
    <ul class="tabs" data-tabs id="example-tabs">
      <li class="tabs-title is-active"><a href="#panel1v" aria-selected="true">Your Snippets</a></li>
      <li class="tabs-title"><a href="#panel2v">Bookmarks</a></li>
    </ul>
  </div>
    <div class="tabs-content" data-tabs-content="example-tabs">
      <div class="tabs-panel is-active" id="panel1v">
        <table class="hover responsive">
      <thead>
        <tr>
          <th class="text-center">snippet</th>
          <th class="text-center">language</th>
          <th class="text-center">posted on</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for snippet in request.user.snippets_created.all %}
        <tr>
          <td><a href="{{ snippet.get_absolute_url }}" title="" class="green-a-tag">{{ snippet.title }}</a></td>
          <td>{{ snippet.language.name }}</td>
          <td>{{ snippet.created }}</td>
          <td>
            <a href="{% url 'snippets:edit_snippet' snippet.pk %}" class="small green button"><span class="fa fa-edit"></span>  Edit</a>
            <a href="{% url 'snippets:del_snippet' snippet.pk %}" class="small button"><span class="fa fa-trash-o"></span>    Delete</a>
          </td>
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
      </div>
      <div class="tabs-panel" id="panel2v">
        <table class="hover responsive">
      <thead>
        <tr>
          <th class="text-center">Snippets</th>
          <th class="text-center">Author</th>
          <th class="text-center">Language</th>
          <th class="text-center">posted on</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for snippet in request.user.bookmarked_snippets.all %}
        <tr>
          <td><a href="{{ snippet.get_absolute_url }}" title="" class="green-a-tag">{{ snippet.title }}</a></td>
          <td>{{ snippet.author.username }}</td>
          <td>{{ snippet.language.name }}</td>
          <td>{{ snippet.created }}</td>
          
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
      </div>
    </div>
</div>
   
{% endblock content %}

snippets/templates/snippets/search.html
{% extends "base_foundations.html" %}
{% block title %}Search{% endblock %}
{% block content %}
  <h3 class="text-center">Found {{ object_list.count }} result{{ object_list.count|pluralize }} for "{{ query }}"</h3>
  {% if object_list %}
    <table class="hover responsive">
      <thead>
        <tr>
          <th class="text-center">snippet</th>
          <th class="text-center">language</th>
          <th class="text-center">author</th>
        </tr>
      </thead>
      <tbody>
        {% for snippet in object_list %}
        <tr>
          <td><a href="{{ snippet.get_absolute_url }}" title="" class="green-a-tag">{{ snippet.title }}</a></td>
          <td>{{ snippet.language.name }}</td>
          <td>{{ snippet.author.username }}</td>
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
  {% else %}
    <p class="text-center">There are no results for your query.</p>
  {% endif %} 
{% endblock %}

snippets/templates/snippets/snippet_confirm_delete.html
{% extends "base_foundations.html" %}

{% block title %}
    Delete
{% endblock title %}

{% block content %}
    <h2>Are you sure?</h2>
    <p>Are You sure you want to delete "{{ object.title }}"</p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="hidden" name="post" value="yes">
      <input type="submit" value="Yes, I'm sure" class="red button">
      <a href="{% url 'snippets:personal_snippets' %}" title="No, take me back" class="green button">No, take me back</a>
    </form>
{% endblock content %}

snippets/templates/snippets/snippet_detail.html
{% extends "base_foundations.html" %}

{% load static %}

{% block title %}
    {{ snippet.title }}
{% endblock title %}

{% block content %}
<style type="text/css" media="screen">
  #editor{
    min-height: 500px;
  }
</style>
<div id="main-body" class="grid-x grid-margin-x">
  <div class="medium-7 cell" id="snippets">
    <div class="callout" id="callout">
      <h2>{{ snippet.title }}</h2>
      <p>
        {{ snippet.description }}
      </p>
      <div class="code-detail float-right">
        <span>posted by </span><a href="{% url 'profile_view' pk=snippet.author.pk username=snippet.author.username %}">{{ snippet.author }}</a>
        <span>language </span><a href="#">{{ snippet.language.name }}</a>
      </div><!-- / code detail -->

      <div id="editor" class="editor">{{ snippet.code }}
      </div> <!-- / code -->

    </div>
  </div>
  <div class="medium-5 cell">
    
  <div class="fb-comments" data-href="http://www.snpet.pythonanywhere.com" data-width="30" data-numposts="5"></div>
  </div>
</div>

<script src="{% static "snippets/js/vendor/src-noconflict/ace.js" %}" type="text/javascript" charset="utf-8"></script>
<script src="static/snippets/js/vendor/src-noconflict/mode-{{ snippet.language.language_mode }}.js" type="text/javascript" charset="utf-8" id="script"></script>

<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/{{ snippet.language.language_mode }}");
</script>
{% endblock content %}