accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from .views import ProfileEditView, ProfileView

urlpatterns = [
    
    # profile urls
    url(r'^profile_edit/$', ProfileEditView.as_view(), name="profile_edit"),
    url(r'^(?P<pk>\d+)/(?P<username>[-\w]+)/profile$',
        ProfileView.as_view(), name="profile_view"),

]

actions/urls.py
from django.conf.urls import url
from .views import snippet_upvote, bookmark_snippets

app_name = "actions"

urlpatterns = [
    url(r'^upvote/$', snippet_upvote, name="upvote"),
    url(r'^bookmark/$', bookmark_snippets, name="bookmark")
]

snippet_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_title = "Snippet Admin"
admin.site.site_header = "Snippet Admin"
admin.site.index_title = "Snippet Administration"

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'', include('snippets.urls', namespace='snippets')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^actions/', include('actions.urls', namespace='actions'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

snippets/urls.py
from django.conf.urls import url
from .views import (
    IndexView,
    AddSnippetView,
    LanguageRegisterView,
    SnippetDetailView,
    FilterView,
    FilterByView,
    PersonalSnippetView,
    SnippetDeleteView,
    SnippetUpdateView,
    SearchView,)

app_name = "snippets"

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^snippets/add/$', AddSnippetView.as_view(), name="add_snippet"),
    url(r'^snippets/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        SnippetDetailView.as_view(), name='snippet_detail'),
    url(r'^snippets/personal/view/$', PersonalSnippetView.as_view(),
        name="personal_snippets"),
    url(r'^snippets/languages/$', FilterByView.as_view(), name="lang_view"),
    url(r'^snippets/languages/(?P<pk>\d+)/$',
        FilterView.as_view(), name="lang_filter"),
    url(r'^snippets/author/$', FilterByView.as_view(), name="author_view"),
    url(r'^snippets/category/$', FilterByView.as_view(), name="category_view"),
    url(r'^snippet/author/(?P<pk>\d+)/$',
        FilterView.as_view(), name="author_filter"),
    url(r'^snippet/category/(?P<pk>\d+)/$',
        FilterView.as_view(), name="category_filter"),

    url(r'^snippets/edit/(?P<pk>\d+)/$', SnippetUpdateView.as_view(), name="edit_snippet"),
    url(r'^snippets/(?P<pk>\d+)/delete$', SnippetDeleteView.as_view(),
        name="del_snippet"),
    url(r'^search/$', SearchView.as_view(), name='snippet_search'),
    url(r'^lang/reg/$', LanguageRegisterView.as_view(), name="language_register"),
    
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    photo = models.ImageField(upload_to="profile/%Y/%m", height_field='height_field', width_field='width_field', blank=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    country = models.CharField(max_length=30, blank=True)
    website = models.URLField(blank=True)   
    
    def __str__(self):
        return "Profile for {}".format(self.user.username)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

snippets/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Language(models.Model):
    name = models.CharField(max_length=50)
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='languages')
    language_mode = models.CharField(max_length=50, default='')
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = 'name',


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"
        ordering = 'name',


class Snippet(models.Model):
    title = models.CharField(max_length=200)
    language = models.ForeignKey(Language, related_name='snippets')
    category = models.ManyToManyField(Category, related_name='snippets')
    slug = models.SlugField(unique_for_date='created', blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="snippets_created")
    description = models.TextField(max_length=300)
    code = models.TextField()
    upvotes = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="snippets_upvoted", blank=True)
    downvotes = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="snippets_downvoted", blank=True)
    bookmarks = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name="bookmarked_snippets", blank=True)
    sample_input = models.TextField(blank=True)
    sample_output = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Snippet, self).save(*args, **kwargs)
        

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("snippets:snippet_detail", args=[self.pk, self.slug])

    class Meta:
        ordering = '-created',

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = 'username', 'email'
        # widget = {
        #     'email': forms.TextInput
        # }


class ProfileEditForm (forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'country', 'website', 'photo'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic import View, UpdateView, DetailView
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from .forms import UserEditForm, ProfileEditForm
from snippets.models import Language
from snippets.forms import LanguageForm
    
    
@method_decorator(login_required, name='dispatch')
class ProfileEditView(View):
    def get(self, request, *args, **kwargs):
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'accounts/profile_edit.html', context)
    
    def post(self, request, *args, **kwargs):
        user_form = UserEditForm( instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST, files=request.FILES) 
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(reverse_lazy('profile_view',
                args=(self.request.user.pk, self.request.user.username)))
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'accounts/profile_edit.html', context)


class ProfileView(DetailView):
    model = User
    template_name = 'accounts/profile.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'user'

    

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock title %}</title>
   <link href="{% static 'accounts/fonts/Tangerine-Regular.ttf' %}" rel="stylesheet">
  {% block assets %}
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <script type="text/javascript">
    $(document).on('click', '.browse', function(){
      var file = $(this).parent().parent().parent().find('.file');
      file.trigger('click');
    });
    $(document).on('change', '.file', function(){
      $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
    });
    </script>
    <link href="{% static 'accounts/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="{% static 'accounts/css/style.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'accounts/css/font-awesome.css' %}" rel="stylesheet"> 
    <script src="{% static 'accounts/js/jquery.min.js' %}"> </script>
    <script src="{% static 'accounts/js/bootstrap.min.js' %}"> </script>
      <style type="text/css" media="screen">
      #editor {
        /** Setting height is also important, otherwise editor wont showup**/
        min-height: 400px;
        height: 100%;
      }
      label[for="id_code"]{
        display: none;
      }
</style>
{% endblock assets %}
<style type="text/css" media="screen">
  nav.navbar.navbar-default {
  height: 30px !important;
  color: #fff;
  background-color: #D95459;
}
div.navbar-header a.navbar-brand {
  color: #fff;
  font-size: 30px;
  font-family: 'Tangerine';
}
</style>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'snippets:index' %}">Snippets</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  </div><!-- /.container-fluid -->
</nav>
  {% block content %}
  {% endblock content %}
 
</body>
</html>

accounts/templates/base_foundations.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
  <link href="{% static 'accounts/fonts/Courgette-Regular.ttf' %}">
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'snippets/css/foundation.css' %}">
  <link type="text/css" media="screen" rel="stylesheet" href="{% static "snippets/css/responsive-tables.css" %}" />
  <link rel="stylesheet" href="{% static 'snippets/css/app.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'snippets/css/foundation-icons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'snippets/css/font-awesome.min.css' %}">
  <script src="{% static 'snippets/js/vendor/jquery.js' %}"></script> 
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11&appId=1869969906626088';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  
  
</head>
<body>
  <div class="grid-container full">
    <div class="title-bar" data-responsive-toggle="navi" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle="navi"></button>
      <div class="title-bar-title"><a href="{% url 'snippets:index' %}" title="">Snippets</a></div>
    </div><!-- / title-bar -->

    <nav class="top-bar" id="navi" data-animate="hinge-in-from-top hinge-out-from-top">
      <div class="top-bar-title show-for-medium"><a href="{% url 'snippets:index' %}" title="">Snippets</a></div>
      <div>
        <div class="top-bar-right">
          <ul class="menu">
            {% if not request.user.is_authenticated %}
            <li><a href="{% url 'account_signup' %}">Signup</a></li>
            <li><a href="{% url 'account_login' %}">Login</a></li>
            {% else %}
            <li>
              <button class="button" type="button" data-toggle="example-dropdown-1">{{ request.user.username }}  
                <span class="fa fa-caret-down"></span>
              </button>
            </li>
            <div class="dropdown-pane" id="example-dropdown-1" data-dropdown data-hover="true" data-hover-pane="true">
              <li>
                <a href="{% url 'profile_view' request.user.pk request.user.username %}">
                  <span class="fa fa-user" aria-hidden></span>    Profile
                </a>
              </li>
              <li>
                <a href="{% url 'profile_edit' %}">
                  <span class="fa fa-pencil-square-o"></span>    Edit Profile
                </a>
              </li>
              <li><a href="{% url 'snippets:personal_snippets' %}"><span class="fa fa-code">    Your Snippets</a></li>
              <li><a href="{% url 'account_logout' %}"><span class="fa fa-sign-out"></span>    Logout</a></li>
            </div>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav><!-- / nav -->
  </div><br>
  <div class="grid-container">
  <div class="grid-x grid-padding-x">
    <div class="callout cell large-9">
      <ul class="grid-x list-unstyled">
        <li class="medium-2 cell"><a href="{% url 'snippets:index' %}">all snippets</a></li>
        <li class="medium-2 cell"><a href="{% url 'snippets:lang_view' %}">by languages</a></li>
        <li class="medium-2 cell"><a href="{% url 'snippets:author_view' %}">by authors</a></li>
        <li class="medium-2 cell"><a href="{% url 'snippets:category_view' %}">by categories</a></li>
        <li class="medium-2 cell"><a href="{% url 'snippets:add_snippet' %}">add a snippet</a></li>
        <li class="medium-2 cell"><a href="{% url 'snippets:personal_snippets' %}">view your snippets</a></li>
      </ul>
    </div>
    <div class="cell large-3">
      <form action="{% url 'snippets:snippet_search' %}">
        <div class="input-group">
          <input class="input-group-field" type="search" placeholder="Search" name="q">
          <div class="input-group-button">
            <button class="button"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </form>
    </div>
  </div>
    {% block content %}
    {% endblock content %}
  </div><br>

  <div class="grid-y">
    <div class="cell shrink footer text-center">
      <p> &copy; 2016 Snippets. All Rights Reserved | Design by samshultz</p>
    </div>
  </div>
  

  
  <script src="{% static 'snippets/js/vendor/what-input.js' %}"></script>
  <script src="{% static 'snippets/js/vendor/foundation.js' %}"></script>
  <script src="{% static 'snippets/js/app.js' %}"></script>
  <script src="{% static 'snippets/js/custom.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $("button#open-tech").hide();
      {% if request.user.is_authenticated %}
        {% if not request.user.languages.all %}
          $("button#open-tech").trigger('click');
        {% endif %}
      {% endif %}
      
    })
  </script>

  <script type="text/javascript" src="{% static "snippets/js/vendor/jquery.min.js" %}"></script>
  <script type="text/javascript" src="{% static "snippets/js/vendor/responsive-tables.js" %}"></script>

</body>
</html>